// The artifact we hand back to the submitter immediately after submit.
// Half generated by Claude (qualitative reasoning, tier copy, integration
// steps), half computed deterministically (revenue projections, math).

export type RecommendedMode = 'prepaid' | 'usage' | 'hybrid';

export interface PricingTier {
  name: string;
  positioning: string;
  price: string;
  unit: string;                  // "/ month" or "per credit pack"
  allotment: string;             // "200 credits" or "1,000 calls" or "Unlimited"
  features: string[];
  highlighted?: boolean;         // mark one as "Most popular"
}

export interface IntegrationStep {
  title: string;
  description: string;
}

export interface RevenueScenario {
  label: string;
  customers: number;
  arpu: number;     // monthly average revenue per user
  mrr: number;
  arr: number;
  assumption: string;
}

export interface NextAction {
  title: string;
  description: string;
  cta: string;
  href?: string;
}

export interface MonetizationPlan {
  // Top-of-page narrative
  headline: string;            // "A prepaid credit wallet fits Sparrwo Scanner best."
  reasoning: string;           // 2-3 sentences

  // Billing mode
  recommendedMode: RecommendedMode;
  modeJustification: string;   // 1 paragraph

  // 3 pricing tiers
  tiers: PricingTier[];

  // Deterministic revenue projections
  projections: {
    pessimistic: RevenueScenario;
    expected:    RevenueScenario;
    optimistic:  RevenueScenario;
    note: string;              // explanation of methodology
  };

  // Integration plan
  integration: {
    estimatedHours: number;
    steps: IntegrationStep[];
    codeSnippet: string;       // pre-substituted with their agent details
    language: 'typescript' | 'python' | 'go';
  };

  // What to do next
  nextActions: NextAction[];

  // Meta
  generatedBy: 'claude' | 'template';
  generatedAt: string;
}
