import Link from 'next/link';
import { notFound } from 'next/navigation';
import { loadAudit } from '@/lib/audit/store';
import type { AuditFinding, AuditRecommendation, CompetitiveBenchmark } from '@/lib/audit/types';
import {
  Wallet, Sparkles, BarChart3, FileText, ShieldCheck, ArrowRight, Download,
  Check, TriangleAlert, X as XIcon, Lightbulb, ExternalLink,
} from 'lucide-react';

export const dynamic = 'force-dynamic';

const MODEL_LABEL: Record<string, string> = {
  freemium: 'Freemium', trial: 'Free trial', paid_only: 'Paid only',
  usage_based: 'Usage-based', hybrid: 'Hybrid', enterprise_only: 'Enterprise only',
  unknown: 'Unclassified',
};

function gradeBand(s: number) {
  if (s >= 85) return { label: 'Best in class', tone: 'brand' };
  if (s >= 70) return { label: 'Solid',         tone: 'brand' };
  if (s >= 55) return { label: 'Mid-pack',      tone: 'amber' };
  return         { label: 'Below average', tone: 'coral' };
}

const SEVERITY_ICON = {
  good: { Icon: Check,          tint: 'bg-brand-500/10 text-brand-700' },
  warn: { Icon: TriangleAlert,  tint: 'bg-amber-100 text-amber-700'    },
  bad:  { Icon: XIcon,          tint: 'bg-coral-400/10 text-coral-600'  },
} as const;

const PRIORITY_LABEL = { high: 'High leverage', medium: 'Medium', low: 'Polish' };

export default async function AuditReport({ params }: { params: { id: string } }) {
  const report = await loadAudit(params.id);
  if (!report) notFound();
  const grade = gradeBand(report.score);

  return (
    <div className="min-h-screen bg-white text-ink-950 font-sans antialiased">

      {/* HEADER */}
      <header className="border-b border-ink-100 bg-white/95 backdrop-blur sticky top-0 z-20">
        <div className="wrap h-[64px] flex items-center justify-between">
          <Link href="/audit" className="flex items-center gap-2.5 font-extrabold text-ink-950">
            <span className="relative w-7 h-7 rounded-lg bg-ink-950 flex items-center justify-center">
              <Wallet size={14} className="text-brand-400" />
              <span className="absolute -top-1 -right-1 w-2.5 h-2.5 rounded-full bg-brand-500 ring-2 ring-white" />
            </span>
            <span className="text-[1.05rem]">Agent<span className="text-brand-500">Mint</span></span>
          </Link>
          <div className="flex items-center gap-3">
            <a href={`/api/audit/${report.url ? params.id : params.id}/pdf`} className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-ink-800 bg-white border border-ink-200 hover:border-ink-400 rounded-lg px-3.5 py-2 transition">
              <Download size={13} /> Download PDF
            </a>
            <Link href="/apply" className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-white bg-ink-950 hover:bg-ink-800 rounded-lg px-3.5 py-2 transition">
              Get a deeper plan <ArrowRight size={13} />
            </Link>
          </div>
        </div>
      </header>

      <main className="wrap py-12 md:py-16 max-w-5xl">

        {/* HERO */}
        <section>
          <div className="flex items-center gap-2 text-[12px] uppercase tracking-[.14em] font-bold text-brand-700">
            <Sparkles size={12} /> Pricing audit · {report.domain}
          </div>
          <h1 className="mt-4 font-extrabold tracking-[-0.03em] leading-[1.04] text-[2.2rem] md:text-[2.8rem] balance">
            {report.headline}
          </h1>
          <p className="mt-5 text-[1.05rem] text-ink-600 leading-relaxed max-w-3xl">{report.summary}</p>

          {report.generatedBy === 'template' && (
            <div className="mt-5 inline-flex items-center gap-2 text-[12px] px-2.5 py-1 rounded-md bg-amber-50 text-amber-700 border border-amber-200">
              <Lightbulb size={12} /> Generated by the deterministic engine · enable Claude (ANTHROPIC_API_KEY) for richer reasoning.
            </div>
          )}

          {/* Score + model */}
          <div className="mt-10 grid md:grid-cols-[1fr_220px] gap-7 items-start">
            <div className="rounded-2xl border border-ink-100 bg-white p-6">
              <div className="text-[11px] uppercase tracking-[.14em] font-bold text-brand-700">Business model</div>
              <h2 className="mt-2 font-extrabold text-[1.5rem] tracking-tight">{MODEL_LABEL[report.businessModel] ?? 'Unclassified'}</h2>
              <p className="mt-3 text-[14px] text-ink-600 leading-relaxed">{report.modelReasoning}</p>
            </div>

            <div className="rounded-2xl border border-ink-100 bg-white p-6 flex flex-col items-center text-center">
              <div className="relative w-36 h-36">
                <svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
                  <circle cx="50" cy="50" r="44" fill="none" stroke="#eef4f1" strokeWidth="10" />
                  <circle cx="50" cy="50" r="44" fill="none" stroke="#10a868" strokeWidth="10"
                    strokeLinecap="round" strokeDasharray={`${(report.score / 100) * 276.46} 276.46`} />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-[2.3rem] font-extrabold tracking-tight tnum text-ink-950">{report.score}</div>
                  <div className="text-[10px] uppercase tracking-[.14em] text-brand-700 font-bold mt-0.5">{grade.label}</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* DIMENSIONS */}
        <section className="mt-12 grid sm:grid-cols-2 md:grid-cols-4 gap-3">
          {report.dimensions.map((d) => {
            const pct = Math.round((d.points / d.max) * 100);
            return (
              <div key={d.key} className="rounded-2xl border border-brand-100 bg-brand-50/40 p-5">
                <div className="text-[11px] uppercase tracking-[.14em] font-bold text-brand-700">{d.label}</div>
                <div className="mt-2 flex items-baseline gap-1.5">
                  <span className="text-[1.85rem] font-extrabold tnum text-ink-950">{d.points}</span>
                  <span className="text-[12.5px] text-ink-500">/ {d.max}</span>
                </div>
                <div className="mt-3 h-1.5 rounded-full bg-white/70 overflow-hidden">
                  <div className="h-full bg-brand-500" style={{ width: `${pct}%` }} />
                </div>
                <p className="mt-3 text-[11.5px] text-ink-500 leading-relaxed mono break-words">{d.detail}</p>
              </div>
            );
          })}
        </section>

        {/* FINDINGS */}
        <section className="mt-14">
          <div className="text-[12px] uppercase tracking-[.14em] font-bold text-brand-700">Findings</div>
          <h2 className="mt-3 font-extrabold text-[1.8rem] md:text-[2.1rem] tracking-tight">What we saw.</h2>
          <div className="mt-6 grid md:grid-cols-2 gap-4">
            {report.findings.map((f, i) => <FindingCard key={i} f={f} />)}
          </div>
        </section>

        {/* COMPETITORS */}
        <section className="mt-14">
          <div className="text-[12px] uppercase tracking-[.14em] font-bold text-brand-700">Competitive comparison</div>
          <h2 className="mt-3 font-extrabold text-[1.8rem] md:text-[2.1rem] tracking-tight">Who else plays this way.</h2>
          <p className="mt-3 text-[15px] text-ink-600 max-w-3xl leading-relaxed">Real companies in your category. Pattern is how they price; takeaway is what to learn from them.</p>
          <div className="mt-6 grid md:grid-cols-3 gap-4">
            {report.competitors.map((c, i) => <CompetitorCard key={i} c={c} />)}
          </div>
        </section>

        {/* RECOMMENDATIONS */}
        <section className="mt-14">
          <div className="text-[12px] uppercase tracking-[.14em] font-bold text-brand-700">Recommendations</div>
          <h2 className="mt-3 font-extrabold text-[1.8rem] md:text-[2.1rem] tracking-tight">Fix list — by leverage.</h2>
          <div className="mt-6 space-y-3">
            {report.recommendations.map((r, i) => <RecCard key={i} r={r} />)}
          </div>
        </section>

        {/* DEEPER PLAN CTA */}
        <section className="mt-16 rounded-2xl bg-ink-950 text-white p-8 md:p-10 relative overflow-hidden">
          <div aria-hidden className="pointer-events-none absolute rounded-full" style={{ width: '22rem', height: '22rem', background: '#10a868', top: '-9rem', right: '-5rem', filter: 'blur(80px)', opacity: 0.32 }} />
          <div className="relative max-w-2xl">
            <div className="text-[12px] uppercase tracking-[.14em] font-bold text-brand-400">Want the operating manual?</div>
            <h2 className="mt-2 font-extrabold text-[1.7rem] md:text-[2rem] tracking-tight leading-tight">For AI agents specifically — get a monetization roadmap.</h2>
            <p className="mt-3 text-[15px] text-ink-300 leading-relaxed">
              This audit reads your *pricing page*. If you're building AI agents and want a full roadmap — integration plan, SDK choices, payment rails, onboarding checklist — that's the next tool.
            </p>
            <div className="mt-6 flex flex-wrap gap-2.5">
              <Link href="/roadmap" className="inline-flex items-center gap-1.5 text-[14.5px] font-semibold text-ink-950 bg-white hover:bg-ink-100 rounded-lg px-5 py-3 transition">
                Open the Roadmap tool <ArrowRight size={14} />
              </Link>
              <Link href="/audit" className="inline-flex items-center gap-1.5 text-[14.5px] font-semibold text-white border border-white/30 hover:border-white/70 rounded-lg px-5 py-3 transition">
                Audit another domain
              </Link>
            </div>
          </div>
        </section>

        <p className="mt-10 text-[12px] text-ink-400 text-center mono">
          Generated {new Date(report.generatedAt).toLocaleString()} · share this URL — no login required
        </p>
      </main>
    </div>
  );
}

function FindingCard({ f }: { f: AuditFinding }) {
  const { Icon, tint } = SEVERITY_ICON[f.severity];
  return (
    <div className="rounded-xl border border-ink-100 bg-white p-5">
      <div className="flex items-center gap-2">
        <span className={`w-7 h-7 rounded-lg ${tint} flex items-center justify-center`}><Icon size={14} strokeWidth={2.4} /></span>
        <span className="text-[11px] uppercase tracking-[.14em] font-bold text-ink-500">{f.area}</span>
      </div>
      <h3 className="mt-3 font-bold text-ink-950 tracking-tight text-[1.02rem]">{f.title}</h3>
      <p className="mt-1 text-[13.5px] text-ink-600 leading-relaxed">{f.body}</p>
    </div>
  );
}

function CompetitorCard({ c }: { c: CompetitiveBenchmark }) {
  return (
    <div className="rounded-xl border border-ink-100 bg-white p-5 flex flex-col">
      <div className="text-[11px] uppercase tracking-[.12em] font-bold text-brand-700">{c.category}</div>
      <h3 className="mt-2 font-extrabold text-ink-950 text-[1.1rem] tracking-tight">{c.name}</h3>
      <p className="mt-3 text-[13.5px] text-ink-600 leading-relaxed">{c.pattern}</p>
      <div className="mt-4 pt-4 border-t border-ink-100 text-[12.5px]">
        <span className="font-bold text-brand-700 uppercase tracking-wider text-[10.5px]">Takeaway · </span>
        <span className="text-ink-700">{c.takeaway}</span>
      </div>
    </div>
  );
}

function RecCard({ r }: { r: AuditRecommendation }) {
  const tone =
    r.priority === 'high'   ? 'border-ink-950 bg-white' :
    r.priority === 'medium' ? 'border-ink-100 bg-white' :
                              'border-ink-100 bg-ink-50/50';
  return (
    <div className={`rounded-xl border-2 ${tone} p-5 md:p-6`}>
      <div className="flex items-center gap-2">
        <span className={`text-[10.5px] uppercase tracking-[.14em] font-bold px-2 py-0.5 rounded-md ${
          r.priority === 'high'   ? 'bg-ink-950 text-white' :
          r.priority === 'medium' ? 'bg-brand-50 text-brand-700' :
                                    'bg-ink-100 text-ink-700'
        }`}>{PRIORITY_LABEL[r.priority]}</span>
      </div>
      <h3 className="mt-3 font-extrabold text-ink-950 text-[1.1rem] tracking-tight">{r.title}</h3>
      <p className="mt-2 text-[14px] text-ink-700 leading-relaxed">{r.body}</p>
      {r.exemplar && (
        <div className="mt-3 pt-3 border-t border-ink-100 text-[12.5px]">
          <span className="font-bold text-ink-800">{r.exemplar.company}: </span>
          <span className="text-ink-600">{r.exemplar.note}</span>
        </div>
      )}
    </div>
  );
}
